#!/bin/sh

pwm='pwm@1c21400'
wifi='mmc@1c10000'
i2c0='i2c@1c2ac00\|i2c@01c2ac00'
i2c1='i2c@1c2b000\|i2c@01c2b000'
i2c2='i2c@1c2b400\|i2c@01c2b400'
w1='w1'
ir='ir@1f02000'
audcodec='codec@1c22c00\|codec@01c22c00'
uart0='serial@1c28000'
uart1='serial@1c28400'
uart2='serial@1c28800'
usb_otg='usb@1c19000'
ehci0='usb@1c1a000'
ohci0='usb@1c1a400'
ehci1='usb@1c1b000'
ohci1='usb@1c1b400'
ehci2='usb@1c1c000'
ohci2='usb@1c1c400'
ehci3='usb@1c1d000'
ohci3='usb@1c1d400'
spi0='spi@1c68000'
spi1='spi@1c69000'
xradio='/etc/modules.d/xradio'
board=$(cat /tmp/sysinfo/board_name)
boardname="${board##*,}"
dts='/tmp/t-dts'

if [ "$2" == "disabled" ]; then
	on_off='okay/disabled'
elif [ "$2" == "okay" ]; then
	on_off='disabled/okay'
fi
if [ "$1" == "wifi" ]; then
  if [[ "$boardname" == "orangepi-zero" || "$boardname" == "orangepi-zero-lts" ]]; then
	sed -i '/'$wifi'/,/\};/ {s/'$on_off'/}' $dts
 	if [ "$2" == "okay" ]; then
	    echo "xradio_wlan" > $xradio
	elif [ "$2" == "disabled" ]; then
	    rm $xradio
	fi
  fi
elif [ "$1" == "i2c0" ]; then
	sed -i '/'$i2c0'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "i2c1" ]; then
	sed -i '/'$i2c1'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "i2c2" ]; then
	sed -i '/'$i2c2'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "w1" ]; then
	sed -i '/'$w1'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "ir" ]; then
	sed -i '/'$ir'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "uart0" ]; then
	sed -i '/'$uart0'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "uart1" ]; then
	sed -i '/'$uart1'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "uart2" ]; then
	sed -i '/'$uart2'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "pwm" ]; then
	sed -i '/'$pwm'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "audcodec" ]; then
	sed -i '/'$audcodec'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "usb_otg" ]; then
	sed -i '/'$usb_otg'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "spi0" ]; then
	sed -i '/'$spi0'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "spi1" ]; then
	sed -i '/'$spi1'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "usb0" ]; then
	sed -i '/'$ehci0'/,/\};/ {s/'$on_off'/}' $dts
	sed -i '/'$ohci0'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "usb1" ]; then
	sed -i '/'$ehci1'/,/\};/ {s/'$on_off'/}' $dts
	sed -i '/'$ohci1'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "usb2" ]; then
	sed -i '/'$ehci2'/,/\};/ {s/'$on_off'/}' $dts
	sed -i '/'$ohci2'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "usb3" ]; then
	sed -i '/'$ehci3'/,/\};/ {s/'$on_off'/}' $dts
	sed -i '/'$ohci3'/,/\};/ {s/'$on_off'/}' $dts
fi
exit 0


