#!/bin/sh

# PA0; gpiosA='0x00'; gpiosN='0x00'	# uart2_tx
# PA1; gpiosA='0x00'; gpiosN='0x01'	# uart2_rx
# PA2; gpiosA='0x00'; gpiosN='0x02'	# uart2_rts
# PA3; gpiosA='0x00'; gpiosN='0x03'	# uart2_cts
# PA4; gpiosA='0x00'; gpiosN='0x04'	# uart0_tx
# PA5; gpiosA='0x00'; gpiosN='0x05'	# uart0_rx
# PA6; gpiosA='0x00'; gpiosN='0x06'
# PA7; gpiosA='0x00'; gpiosN='0x07'
# PA10; gpiosA='0x00'; gpiosN='0x0a'
# PA11; gpiosA='0x00'; gpiosN='0x0b'	# i2c0_scl
# PA12; gpiosA='0x00'; gpiosN='0x0c' 	# i2c0_sda
# PA13; gpiosA='0x00'; gpiosN='0x0d' 	# 
# PA14; gpiosA='0x00'; gpiosN='0x0e' 	# 
# PA15; gpiosA='0x00'; gpiosN='0x0f' 	# 
# PA16; gpiosA='0x00'; gpiosN='0x10' 	# 
# PA18; gpiosA='0x00'; gpiosN='0x12' 	# i2c1_scl
# PA19; gpiosA='0x00'; gpiosN='0x13' 	# i2c1_sda
# PG6; gpiosA='0x06'; gpiosN='0x06'	# uart1_tx
# PG7; gpiosA='0x06'; gpiosN='0x07'	# uart1_rx

pwm='pwm@1c21400'
wifi='mmc@1c10000'
i2c0='i2c@1c2ac00\|i2c@01c2ac00'
i2c1='i2c@1c2b000\|i2c@01c2b000'
i2c2='i2c@1c2b400\|i2c@01c2b400'
w1='w1'
ir='ir@1f02000'
audcodec='codec@1c22c00\|codec@01c22c00'
uart0='serial@1c28000'
uart1='serial@1c28400'
uart2='serial@1c28800'
usb_otg='usb@1c19000'
ehci0='usb@1c1a000'
ohci0='usb@1c1a400'
ehci1='usb@1c1b000'
ohci1='usb@1c1b400'
ehci2='usb@1c1c000'
ohci2='usb@1c1c400'
ehci3='usb@1c1d000'
ohci3='usb@1c1d400'
spi0='spi@1c68000'
spi1='spi@1c69000'
xradio='/etc/modules.d/xradio'
board=$(cat /tmp/sysinfo/board_name)
boardname="${board##*,}"
dts='/tmp/t-dts'

if [ "$2" == "disabled" ]; then
	on_off='okay/disabled'
elif [ "$2" == "okay" ]; then
	on_off='disabled/okay'
fi
if [ "$1" == "wifi" ]; then
  if [[ "$boardname" == "orangepi-zero" || "$boardname" == "orangepi-zero-lts" ]]; then
	sed -i '/'$wifi'/,/\};/ {s/'$on_off'/}' $dts
 	if [ "$2" == "okay" ]; then
	    echo "xradio_wlan" > $xradio
	elif [ "$2" == "disabled" ]; then
	    rm $xradio
	fi
  fi
elif [ "$1" == "w1pin" ]; then
 	if [ "$2" == "PG6" ]; then
		gpiosA='0x06'; gpiosN='0x06'
	elif [ "$2" == "PG6" ]; then
		gpiosA='0x06'; gpiosN='0x07'
	elif [ "$2" == "PA0" ]; then
		gpiosA='0x00'; gpiosN='0x00'
	elif [ "$2" == "PA1" ]; then
		gpiosA='0x00'; gpiosN='0x01'
	elif [ "$2" == "PA2" ]; then
		gpiosA='0x00'; gpiosN='0x02'
	elif [ "$2" == "PA3" ]; then
		gpiosA='0x00'; gpiosN='0x03'
	elif [ "$2" == "PA4" ]; then
		gpiosA='0x00'; gpiosN='0x04'
	elif [ "$2" == "PA5" ]; then
		gpiosA='0x00'; gpiosN='0x05'
	elif [ "$2" == "PA6" ]; then
		gpiosA='0x00'; gpiosN='0x06'
	elif [ "$2" == "PA7" ]; then
		gpiosA='0x00'; gpiosN='0x07'
	elif [ "$2" == "PA10" ]; then
		gpiosA='0x00'; gpiosN='0x0a'
	elif [ "$2" == "PA11" ]; then
		gpiosA='0x00'; gpiosN='0x0b'
	elif [ "$2" == "PA12" ]; then
		gpiosA='0x00'; gpiosN='0x0c'
	elif [ "$2" == "PA13" ]; then
		gpiosA='0x00'; gpiosN='0x0d'
	elif [ "$2" == "PA14" ]; then
		gpiosA='0x00'; gpiosN='0x0e'
	elif [ "$2" == "PA15" ]; then
		gpiosA='0x00'; gpiosN='0x0f'
	elif [ "$2" == "PA16" ]; then
		gpiosA='0x00'; gpiosN='0x10'
	elif [ "$2" == "PA18" ]; then
		gpiosA='0x00'; gpiosN='0x12'
	elif [ "$2" == "PA19" ]; then
		gpiosA='0x00'; gpiosN='0x13'
	fi
	sed -i '/w1_pins {/,/\};/ {s/pins.*\"\;/pins = \"'$2'\"\;/}' $dts
	sed -i '/w1 {/,/\};/ {s/0x0a\ .*\ 0x00/0x0a\ '$gpiosA'\ '$gpiosN'\ 0x00/}' $dts
elif [ "$1" == "i2c0" ]; then
	sed -i '/'$i2c0'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "i2c1" ]; then
	sed -i '/'$i2c1'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "i2c2" ]; then
	sed -i '/'$i2c2'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "w1" ]; then
	sed -i '/w1 {/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "ir" ]; then
	sed -i '/'$ir'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "uart0" ]; then
	sed -i '/'$uart0'/,/\};/ {s/'$on_off'/}' $dts
	sed -i '/'$pwm'/,/\};/ {s/okay/disabled/}' $dts
elif [ "$1" == "uart1" ]; then
	sed -i '/'$uart1'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "uart2" ]; then
	sed -i '/'$uart2'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "pwm" ]; then
	sed -i '/'$pwm'/,/\};/ {s/'$on_off'/}' $dts
	sed -i '/'$uart0'/,/\};/ {s/okay/disabled/}' $dts
elif [ "$1" == "audcodec" ]; then
	sed -i '/'$audcodec'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "usb_otg" ]; then
	sed -i '/'$usb_otg'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "spi0" ]; then
	sed -i '/'$spi0'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "spi1" ]; then
	sed -i '/'$spi1'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "usb0" ]; then
	sed -i '/'$ehci0'/,/\};/ {s/'$on_off'/}' $dts
	sed -i '/'$ohci0'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "usb1" ]; then
	sed -i '/'$ehci1'/,/\};/ {s/'$on_off'/}' $dts
	sed -i '/'$ohci1'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "usb2" ]; then
	sed -i '/'$ehci2'/,/\};/ {s/'$on_off'/}' $dts
	sed -i '/'$ohci2'/,/\};/ {s/'$on_off'/}' $dts
elif [ "$1" == "usb3" ]; then
	sed -i '/'$ehci3'/,/\};/ {s/'$on_off'/}' $dts
	sed -i '/'$ohci3'/,/\};/ {s/'$on_off'/}' $dts
fi
exit 0



