#!/bin/sh

cat /etc/config/cpufreq_scaling > /dev/null
if [ $? == 1 ]; then 
echo > /etc/config/cpufreq_scaling
fi

while uci -q delete cpufreq_scaling.@cpufreq[0]; do :; done
uci -q commit cpufreq_scaling
uci -q batch <<-EOF
 set cpufreq_scaling.cpufreq="cpufreq"
 set cpufreq_scaling.@cpufreq[0].min_freq="480000"
 set cpufreq_scaling.@cpufreq[0].max_freq="1008000"
 set cpufreq_scaling.@cpufreq[0].governor="ondemand"
 set cpufreq_scaling.@cpufreq[0].upthreshold="25"
 set cpufreq_scaling.@cpufreq[0].factor="10"
EOF
sleep 1
uci -q commit cpufreq_scaling
