#!/bin/sh
#/etc/init.d/cpufreq_scaling disable

cat /etc/config/cpufreq_scaling > /dev/null
if [ $? == 1 ]; then 
echo > /etc/config/cpufreq_scaling
fi

while uci -q delete cpufreq_scaling.@cpufreq[0]; do :; done
uci -q commit cpufreq_scaling
uci -q batch <<-EOF
 set cpufreq_scaling.cpufreq="cpufreq"
 set cpufreq_scaling.@cpufreq[0].min_freq="480000"
 set cpufreq_scaling.@cpufreq[0].max_freq="1008000"
 set cpufreq_scaling.@cpufreq[0].governor="ondemand"
 set cpufreq_scaling.@cpufreq[0].upthreshold="25"
 set cpufreq_scaling.@cpufreq[0].factor="10"
EOF
sleep 1
uci -q commit cpufreq_scaling

sed -i "/boot-config-spi\/index.cgi/d" /www/menu.html 2> /dev/null
	# К моей вебке cyberwrt - раскомментировать если будет использоваться ####
sed -i 3i\ '<li><a href=/cgi-bin/modules/boot-config-spi/index.cgi>'Boot-config-spi'</a></li>' /www/menu.html 2> /dev/null
	# К вебке cyberwrt - закомментировть если НЕ будет использоваться ####
#sed -i 3i\ '<a href=/cgi-bin/modules/boot-config-spi/index.cgi><div class=left>'Boot-config-spi'</div></a>' /www/menu.html 2> /dev/null

