#!/bin/sh

#i2c_adres=0x44
#i2c_dev=0

i2c_adres=$(uci get tda7313.@tda7313[0].i2c_adres)
i2c_dev=$(uci get tda7313.@tda7313[0].i2c_dev)

tfiles='/tmp/hh'

volume='0'
bass='96' # 0x60
treble='112' # 0x70
spec_LF='128' # 0x80 # 128+0+$vol_spec
spec_RF='160' # 0xA0 # 128+32+$vol_spec
spec_LR='192' # 0xC0 # 128+64+$vol_spec
spec_RR='224' # 0xE0 # 128+96+$vol_spec

switch='64' # 0x40 # 64+0
#switch1='65' # 0x41 # 64+1
#switch2='66' # 0x42 # 64+2

LOUD_OFF='4'
LOUD_ON='0'

LOUD_ON3db='0'
LOUD_ON2db='8'
LOUD_ON1db='16'
LOUD_ON0db='24'
#example switch1+LOUD_ON3db:  
# vol='1'; hh=$(($switch + $vol + $LOUD_ON + $LOUD_ON3db)); write_CMD

write_CMD () {
 i2cset -f -y $i2c_dev $i2c_adres $hh
}

tda7313_init () {
 echo -e volume 40'\n'subtrebl 20'\n'subbas 15'\n'bass 12'\n'treble 12'\n'switch 1 > $tfiles

 vol='40'
 var=63
 let "var -= $vol"
 hh=$(($volume + $var))
 write_CMD

 vol='20'
 var=31
 let "var -= $vol"
 hh=$(($spec_LF + $var))
 write_CMD
 hh=$(($spec_RF + $var))
 write_CMD

 vol='15'
 var=31
 let "var -= $vol"
 hh=$(($spec_LR + $var))
 write_CMD
 hh=$(($spec_RR + $var))
 write_CMD

 vol='12'
 var=23
 let "var -= $vol"
 hh=$(($bass + $var))
 write_CMD
 hh=$(($treble + $var))
 write_CMD

 vol='1' # switch1
 hh=$(($switch + $vol + $LOUD_OFF))
 write_CMD
}

test_reg () {
 echo 
 cat /tmp/hh
 echo 
 echo "  reg+vol: "$hh
}
###

if [[ "$1" == "tda7313_init" || "$1" == "init" ]]; then
    tda7313_init
#    echo $1 "OK"
elif [[ "$1" == "switch" || "$1" == "aux" || "$1" == "input" ]]; then
  if [[ "$2" -ge "0" && "$2" -le "3" ]]; then
#    hh=$(($switch + $2))
    hh=$(($switch + $2 + $LOUD_OFF))
    write_CMD
    volm=$(sed '/switch /!d' $tfiles | awk '{print $2}')
    sed -i '/switch /s/'$volm'/'$2'/g' $tfiles
  fi
# volume
elif [ "$1" == "volume" ]; then
  if [[ "$2" -ge "0" && "$2" -le "63" ]]; then
    var=63
    let "var -= $2"
    hh=$(($volume + $var))
    write_CMD
    volm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    sed -i '/'$1' /s/'$volm'/'$2'/g' $tfiles
  elif [[ "$2" == "+" || "$2" == "-" ]]; then
    vlm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    if [[ "$2" == "-" && "$vlm" -eq "63" ]]; then
      let "vlm "$2"= 1"
    elif [[ "$vlm" -eq "0" && "$2" == "+" ]]; then
      let "vlm "$2"= 1"
    elif [[ "$vlm" -gt "0" && "$vlm" -lt "63" ]]; then
      let "vlm "$2"= 1"
    fi
    var=63
    let "var -= $vlm"
    hh=$(($volume + $var))
    write_CMD
    volm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    sed -i '/'$1' /s/'$volm'/'$vlm'/g' $tfiles
  fi
# treble
elif [ "$1" == "treble" ]; then
  if [[ "$2" -ge "0" && "$2" -le "15" ]]; then
    if [ "$2" -le "7" ]; then
	hh=$(($treble + $2))
    else
	var=23
	let "var -= $2"
	hh=$(($treble + $var))
    fi
    write_CMD
    volm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    sed -i '/'$1' /s/'$volm'/'$2'/g' $tfiles
  elif [[ "$2" == "+" || "$2" == "-" ]]; then
    vlm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    if [[ "$2" == "-" && "$vlm" -eq "15" ]]; then
      let "vlm "$2"= 1"
    elif [[ "$vlm" -eq "0" && "$2" == "+" ]]; then
      let "vlm "$2"= 1"
    elif [[ "$vlm" -gt "0" && "$vlm" -lt "15" ]]; then
      let "vlm "$2"= 1"
    fi
    if [ "$vlm" -le "7" ]; then
	hh=$(($treble + $vlm))
    else
      var=23
      let "var -= $vlm"
      hh=$(($treble + $var))
    fi
    write_CMD
    volm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    sed -i '/'$1' /s/'$volm'/'$vlm'/g' $tfiles
  fi
# sbass - streble
elif [[ "$1" == "sbass" || "$1" == "streble" ]]; then
  if [ "$1" == "sbass" ]; then
      tmbr='subbas'
  elif [ "$1" == "streble" ]; then
      tmbr='subtrebl'
  fi
  volm=$(sed '/'$tmbr' /!d' $tfiles | awk '{print $2}')
  if [[ "$2" -ge "0" && "$2" -le "31" ]]; then
    var=31
    let "var -= $2"
    if [ "$1" == "sbass" ]; then
      hh=$(($spec_LR + $var))
      write_CMD
      hh=$(($spec_RR + $var))
      write_CMD
    elif [ "$1" == "streble" ]; then
      hh=$(($spec_LF + $var))
      write_CMD
      hh=$(($spec_RF + $var))
      write_CMD
    fi
    sed -i '/'$tmbr' /s/'$volm'/'$2'/g' $tfiles
  elif [[ "$2" == "+" || "$2" == "-" ]]; then
    vlm=$(sed '/'$tmbr' /!d' $tfiles | awk '{print $2}')
    if [[ "$2" == "-" && "$vlm" -eq "31" ]]; then
      let "vlm "$2"= 1"
    elif [[ "$vlm" -eq "0" && "$2" == "+" ]]; then
      let "vlm "$2"= 1"
    elif [[ "$vlm" -gt "0" && "$vlm" -lt "31" ]]; then
      let "vlm "$2"= 1"
    fi
    var=31
    let "var -= $vlm"
    if [ "$1" == "sbass" ]; then
      hh=$(($spec_LR + $var))
      write_CMD
      hh=$(($spec_RR + $var))
      write_CMD
    elif [ "$1" == "streble" ]; then
      hh=$(($spec_LF + $var))
      write_CMD
      hh=$(($spec_RF + $var))
      write_CMD
    fi
    sed -i '/'$tmbr' /s/'$volm'/'$vlm'/g' $tfiles
  fi
# bass
elif [ "$1" == "bass" ]; then
  if [[ "$2" -ge "0" && "$2" -le "15" ]]; then
    if [ "$2" -le "7" ]; then
	hh=$(($bass + $2))
    else
	var=23
	let "var -= $2"
	hh=$(($bass + $var))
    fi
    write_CMD
    volm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    sed -i '/'$1' /s/'$volm'/'$2'/g' $tfiles
  elif [[ "$2" == "+" || "$2" == "-" ]]; then
    vlm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    if [[ "$2" == "-" && "$vlm" -eq "15" ]]; then
      let "vlm "$2"= 1"
    elif [[ "$vlm" -eq "0" && "$2" == "+" ]]; then
      let "vlm "$2"= 1"
    elif [[ "$vlm" -gt "0" && "$vlm" -lt "15" ]]; then
      let "vlm "$2"= 1"
    fi
    if [ "$vlm" -le "7" ]; then
	hh=$(($bass + $vlm))
    else
      var=23
      let "var -= $vlm"
      hh=$(($bass + $var))
    fi
    write_CMD
    volm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    sed -i '/'$1' /s/'$volm'/'$vlm'/g' $tfiles
  fi
elif [ "$1" == "LF" ]; then
  if [[ "$2" -ge "0" && "$2" -le "31" ]]; then
    var=31
    let "var -= $2"
    hh=$(($spec_LF + $var))
    write_CMD
    volm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    sed -i '/'$1' /s/'$volm'/'$2'/g' $tfiles
  fi
elif [ "$1" == "RF" ]; then
  if [[ "$2" -ge "0" && "$2" -le "31" ]]; then
    var=31
    let "var -= $2"
    hh=$(($spec_RF + $var))
    write_CMD
    volm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    sed -i '/'$1' /s/'$volm'/'$2'/g' $tfiles
  fi
elif [ "$1" == "LR" ]; then
  if [[ "$2" -ge "0" && "$2" -le "31" ]]; then
    var=31
    let "var -= $2"
    hh=$(($spec_LR + $var))
    write_CMD
    volm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    sed -i '/'$1' /s/'$volm'/'$2'/g' $tfiles
  fi
elif [ "$1" == "RR" ]; then
  if [[ "$2" -ge "0" && "$2" -le "31" ]]; then
    var=31
    let "var -= $2"
    hh=$(($spec_RR + $var))
    write_CMD
    volm=$(sed '/'$1' /!d' $tfiles | awk '{print $2}')
    sed -i '/'$1' /s/'$volm'/'$2'/g' $tfiles
  fi
elif [[ "$1" == "?" || "$1" == "-?" || "$1" == "--?" || "$1" == "help" ]]; then
    echo -e '\t' tda7313 "init"'\t'"#" initialization'\n\n\t' tda7313 "<type>" "<value>"
    echo -e '\t' '\t' "type:"'\t'"init, volume, bass, treble, streble, sbass, switch, "
    echo -e '\t' '\t' "type:"'\t'"LF, RF, LR, RR"'\n\n\t' '\t' "value:"'\t'"+, -, 0-63"'\n'
    echo -e '\t' Example:'\n\t' tda7313 "volume +"'\t'"#" Volume level "+".
    echo -e '\t' tda7313 "volume -"'\t'"#" Volume level "-"'\n\t' tda7313 "volume 55"'\t'"#" Volume level "55"
fi
#test_reg
exit 0
