#!/bin/sh
/etc/init.d/i2c_HD44780.init disable

sed -i "/i2c_hd44780\/index.cgi/d" /www/menu.html 2> /dev/null

	# К моей вебке cyberwrt - раскомментировать если будет использоваться ####
sed -i 3i\ '<li><a href=/cgi-bin/modules/i2c_hd44780/index.cgi>'i2c-LCD-monitor'</a></li>' /www/menu.html 2> /dev/null
	# К вебке cyberwrt - закомментировть если НЕ будет использоваться ####
#sed -i 3i\ '<a href=/cgi-bin/modules/i2c_hd44780/index.cgi><div class=left>'i2c-LCD-monitor'</div></a>' /www/menu.html 2> /dev/null

