#!/bin/sh

sed -i "/web-ir-remote\/index.cgi/d" /www/menu.html 2> /dev/null
	# К моей вебке cyberwrt - раскомментировать если будет использоваться ####
sed -i 3i\ '<li><a href=/cgi-bin/modules/web-ir-remote/index.cgi>'Irc-remote-setup'</a></li>' /www/menu.html 2> /dev/null
	# К вебке cyberwrt - закомментировть если НЕ будет использоваться ####
#sed -i 3i\ '<a href=/cgi-bin/modules/web-ir-remote/index.cgi><div class=left>'Irc-remote-setup'</div></a>' /www/menu.html 2> /dev/null

