#!/bin/sh
CNF_REAL="ds18b20"
VIZUAL_HTML="/tmp/tstatgpio.html"
WWW_HTML="/www/tstatgpio.html"
VAR_HRZS="/var/hrzs"
CONF_RAB="/tmp/gpiotemp"
TTESTT="/var/zawis.gp"

outOff() {
    local ds_num=$1
    local out_power=$(uci -q get "${CNF_REAL}.@ds18b20_s${ds_num}[0].pwout")
    local oInvert=$(uci -q get "${CNF_REAL}.@Gpio1Wr[0].oInvert")
    [ -z "$out_power" ] && return
    if [ "$oInvert" = "0" ]; then
        echo 0 > "/sys/class/gpio/gpio${out_power}/value"
    else
        echo 1 > "/sys/class/gpio/gpio${out_power}/value"
    fi
}

outOn() {
    local ds_num=$1
    local out_power=$(uci -q get "${CNF_REAL}.@ds18b20_s${ds_num}[0].pwout")
    local oInvert=$(uci -q get "${CNF_REAL}.@Gpio1Wr[0].oInvert")
    [ -z "$out_power" ] && return
    if [ "$oInvert" = "0" ]; then
        echo 1 > "/sys/class/gpio/gpio${out_power}/value"
    else
        echo 0 > "/sys/class/gpio/gpio${out_power}/value"
    fi
}

testAllarm() {
    local ds_num=$1 tips_p1=$2 conf_Totkl1=$3 t_alarm=$4 t_stat=$5 term_on=$6
    local Tsn_sor=$(awk -v t="$sen_sor" 'BEGIN {print t*1000}')
    
    if [ "$tips_p1" = "$term_on" ]; then
        outOff "$ds_num"
    else
        local hrzs=$(awk -v ds="ds$ds_num" '$1==ds {print $2}' "$VAR_HRZS")
        if [ "$tips_p1" = "$t_stat" ]; then
            if [ "$hrzs" = "1" ]; then    
                if [ "$Tsn_sor" -le "$conf_Totkl1" ]; then
                    outOn "$ds_num"
                else
                    sed -i "s/ds${ds_num} 1/ds${ds_num} 0/" "$VAR_HRZS"
                    outOff "$ds_num"
                fi
            else
                if [ "$Tsn_sor" -le "$t_alarm" ]; then
                    outOn "$ds_num"
                    sed -i "s/ds${ds_num} 0/ds${ds_num} 1/" "$VAR_HRZS"
                fi
            fi
        else
            if [ "$hrzs" != "0" ] && [ "$hrzs" != "1" ]; then
                sed -i "s/ds${ds_num} 0/ds${ds_num} 1/" "$VAR_HRZS"
            fi
            hrzs=$(awk -v ds="ds$ds_num" '$1==ds {print $2}' "$VAR_HRZS")
            if [ "$hrzs" = "1" ]; then            
                if [ "$Tsn_sor" -ge "$conf_Totkl1" ]; then
                    outOn "$ds_num"
                else
                    outOff "$ds_num"
                    sed -i "s/ds${ds_num} 1/ds${ds_num} 0/" "$VAR_HRZS"
                fi
            else
                if [ "$Tsn_sor" -ge "$t_alarm" ]; then
                    outOn "$ds_num"
                    sed -i "s/ds${ds_num} 0/ds${ds_num} 1/" "$VAR_HRZS"
                fi
            fi
        fi
    fi
}

kollwo=$(find /sys/devices/w1_bus_master1 -maxdepth 1 -name "28-*" -o -name "10-*" 2>/dev/null | wc -l)
if [ "$kollwo" = "0" ]; then exit 0; fi

enabl=$(uci -q get ds18b20.@Gpio1Wr[0].enabled0)
if [ "$enabl" != "1" ]; then exit 0; fi

init18b20
ln -sf "$VIZUAL_HTML" "$WWW_HTML"
sdf=0

true > "$VAR_HRZS"
for i in 0 1 2 3 4 5 6 7 8 9; do echo "ds$i 1" >> "$VAR_HRZS"; done

while true; do
    rm -f /tmp/thermgpio "$CONF_RAB" 2>/dev/null
    
    kollwo=$(uci -q show ds18b20 | grep -c "id_sensor=")
    nomer_ds=0
    perem=16
    
    while [ "$nomer_ds" -lt "$kollwo" ]; do
        rm -f /etc/config/.ds18* 2>/dev/null
        true > "$CONF_RAB"
        out_power=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].pwout")
        
        nedel=$(date +%u)
        imDenNed=""
        if [ "$nedel" = "2" ]; then imDenNed="Tue_"
        elif [ "$nedel" = "3" ]; then imDenNed="Wed_"
        elif [ "$nedel" = "4" ]; then imDenNed="Thu_"
        elif [ "$nedel" = "5" ]; then imDenNed="Fri_"
        elif [ "$nedel" = "6" ]; then imDenNed="Sat_"
        elif [ "$nedel" = "7" ]; then imDenNed="Sun_"
        fi
        
        hourTime1=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].${imDenNed}t1ime")
        minuteTime1=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].${imDenNed}m1ime")
        hourTime2=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].${imDenNed}t2ime")
        minuteTime2=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].${imDenNed}m2ime")
        hourTime3=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].${imDenNed}t3ime")
        minuteTime3=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].${imDenNed}m3ime")
        
        dadatt=$(date +%H%M)
        if [ "$dadatt" -ge "${hourTime3}${minuteTime3}" ] 2>/dev/null; then
            gradusOff=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].${imDenNed}gra3dus")
        elif [ "$dadatt" -ge "${hourTime2}${minuteTime2}" ] 2>/dev/null; then
            gradusOff=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].${imDenNed}gra2dus")
        elif [ "$dadatt" -ge "${hourTime1}${minuteTime1}" ] 2>/dev/null; then
            gradusOff=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].${imDenNed}gradus")
        else
            gradusOff=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].${imDenNed}gra0dus")
        fi

        tips_p1=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].tipsensr")
        term_on="termometr" ; t_stat="termostat" ; s_off="send"
        
        if [ "$tips_p1" = "$term_on" ]; then
            outOff "$nomer_ds"
        else
            sdsd_sr=$(cat "/sys/class/gpio/gpio${out_power}/value" 2>/dev/null)
            if [ -n "$sdsd_sr" ]; then
                Hist=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].hister")
                conf_Hist=$(awk -v h="$Hist" 'BEGIN {print h*1000}')
                conf_Totkl1=$(awk -v g="$gradusOff" 'BEGIN {print g*1000}')
                if [ "$tips_p1" = "$t_stat" ]; then
                    t_alarm=$((conf_Totkl1 - conf_Hist))
                else
                    t_alarm=$((conf_Totkl1 + conf_Hist))
                fi
            else
                uci set "ds18b20.@ds18b20_s${nomer_ds}[0].tipsensr=termometr"
                uci commit ds18b20
            fi
        fi
        
        ID_hex=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].id_sensor")
        w1_path="/sys/bus/w1/devices/${ID_hex}/w1_slave"
        [ ! -f "$w1_path" ] && w1_path="/sys/bus/w1/drivers/w1_slave_driver/${ID_hex}/w1_slave"
        
        ten_sr=$(awk -F= '/t=/ {printf "%.1f\n", $2/1000}' "$w1_path" 2>/dev/null)
        echo "sn_sor $ten_sr" >> "$CONF_RAB"
        sen_sor=$ten_sr
        
        if [ -n "$sen_sor" ]; then
            testAllarm "$nomer_ds" "$tips_p1" "$conf_Totkl1" "$t_alarm" "$t_stat" "$term_on"
        else
            outOff "$nomer_ds"
        fi
        
        lcd_on=$(uci -q get "${CNF_REAL}.@Gpio1Wr[0].pu_Skryp")
        if [ "$lcd_on" = "1" ]; then echo "t_sn${nomer_ds} ${sen_sor}" >> /tmp/d_x; fi
        
        D_minuta=$(date +%M)
        Datata=$(date +%b.%d.%Y)
        Dfdd=$(date +%T)
        logns=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].logns")
        
        if [ "$nomer_ds" -lt "$kollwo" ]; then
            echo "zwser 1" > "$TTESTT"
            perem=$((perem + 1))
            sed -i -r "${perem}s,>[^<]*</,>${logns}: ${Datata} ${Dfdd}</," "$VIZUAL_HTML" 2>/dev/null
            perem=$((perem + 1))
            sed -i -r "${perem}s,>[^<]*</,>${sen_sor}\°C</," "$VIZUAL_HTML" 2>/dev/null
        fi

        interv=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].times")
        Filter=""
        if [ "$interv" = "2" ]; then Filter="00|02|04|06|08|10|12|14|16|18|20|22|24|26|28|30|32|34|36|38|40|42|44|46|48|50|52|54|56|58"
        elif [ "$interv" = "5" ]; then Filter="00|05|10|15|20|25|30|35|40|45|50|55"
        elif [ "$interv" = "10" ]; then Filter="00|10|20|30|40|50"
        elif [ "$interv" = "15" ]; then Filter="00|15|30|45"
        elif [ "$interv" = "20" ]; then Filter="00|20|40"
        elif [ "$interv" = "30" ]; then Filter="00|30"
        elif [ "$interv" = "60" ]; then Filter="00"
        fi
        
        if [ -n "$Filter" ] && echo "$D_minuta" | grep -qE "^(${Filter})$"; then
            if [ "$nomer_ds" = "$sdf" ]; then
                if [ "$(uci -q get ds18b20.@Gpio1Wr[0].ftp_svr)" = "1" ]; then
                    ALL_string=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].folder")
                    if [ -n "$ALL_string" ]; then
                        NacaloFold_Dir1="${ALL_string%/*}/"
                        KonecFold_Dir1="${ALL_string##*/}"
                        mkdir -p "${NacaloFold_Dir1}${Datata}"
                        chmod 777 "${NacaloFold_Dir1}${Datata}"
                        Fold_Dir1="${NacaloFold_Dir1}${Datata}/${tips_p1}${KonecFold_Dir1}"
                        echo "$(date +%T) \t T: ${sen_sor}*C" >> "$Fold_Dir1"
                        cp -f "$VIZUAL_HTML" "${ALL_string}.html" 2>/dev/null
                    fi
                fi
                
                mac_addr=$(ifconfig | grep -E "HWaddr|ether" | awk '{print $5 ? $5 : $2}' | head -n 1 | tr -d ':')
                
                echo "#${mac_addr}" > "/var/log/narodgpiomon.Dev${nomer_ds}"
                echo "#${ID_hex}#${sen_sor}" >> "/var/log/narodgpiomon.Dev${nomer_ds}"
                echo "##" >> "/var/log/narodgpiomon.Dev${nomer_ds}"
                
                if uci -q get ds18b20.@ds18b20_s${nomer_ds}[0].enab_nar | grep -q "1"; then
                    if [ "$sdf" = "0" ]; then
                        nar_all="/var/log/narodgpiomon_all"
                        echo "#${mac_addr}" > "$nar_all"
                        
                        stst=0
                        while [ "$stst" -lt "$kollwo" ]; do
                            if [ "$(uci -q get "${CNF_REAL}.@ds18b20_s${stst}[0].enab_nar")" = "1" ]; then
                                s_id=$(uci -q get "${CNF_REAL}.@ds18b20_s${stst}[0].id_sensor")
                                if [ -f "/var/log/narodgpiomon.Dev${stst}" ]; then
                                    grep "$s_id" "/var/log/narodgpiomon.Dev${stst}" >> "$nar_all"
                                fi
                            fi
                            stst=$((stst + 1))
                        done
                        echo "##" >> "$nar_all"
                        
                        serv_down=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].serv_d")
                        serv_port=$(uci -q get "${CNF_REAL}.@ds18b20_s${nomer_ds}[0].serv_port")
                        
                        if [ -n "$serv_down" ] && [ -n "$serv_port" ]; then
                            log_nard="/var/log/narodgpiomon.log"
                            cat "$nar_all" | nc "$serv_down" "$serv_port" > "$log_nard" 2>/dev/null
                            
                            tssst_cycl=0
                            while ! grep -q "OK" "$log_nard" && [ "$tssst_cycl" -lt 5 ]; do
                                sleep 1
                                cat "$nar_all" | nc "$serv_down" "$serv_port" > "$log_nard" 2>/dev/null
                                tssst_cycl=$((tssst_cycl + 1))
                            done
                        fi
                    fi
                fi
                sdf=$((sdf + 1))
            fi
        else
            sdf=0
        fi
        nomer_ds=$((nomer_ds + 1))
    done
    
    lcd_on=$(uci -q get "${CNF_REAL}.@Gpio1Wr[0].pu_Skryp")
    cmd=$(uci -q get "${CNF_REAL}.@Gpio1Wr[0].imya_skript")
    if [ "$lcd_on" = "1" ] && [ -f "/usr/sbin/$cmd" ]; then
        sh "/usr/sbin/$cmd"
    fi
    
    sleep 2
    rm -f /tmp/d_x 2>/dev/null
done
exit 0
