package w1-gpio-custom

# =====================================================================
# НАЛАШТУВАННЯ 1-WIRE ШИН (w1-gpio-custom)
# Поля для кожної шини:
#   enabled:    1 — увімкнути шину, 0 — ігнорувати при старті
#   id:         Унікальний ID шини для ядра (має бути різним)
#   pin:        Номер GPIO піна на вашому роутері
#   od:         1 — Open Drain (відкритий стік), 0 — звичайний Push-Pull
#   resolution: Точність датчиків DS18B20 на шині (9, 10, 11 або 12 біт)
# =====================================================================

config bus 'bus0'
	option enabled '1'
	option id '1'
	option pin '10'
	option od '1'
	option resolution '12'

config bus 'bus1'
	option enabled '0'
	option id '2'
	option pin '17'
	option od '1'
	option resolution '10'

config bus 'bus2'
	option enabled '0'
	option id '3'
	option pin '18'
	option od '1'
	option resolution '12'

config bus 'bus3'
	option enabled '0'
	option id '4'
	option pin '23'
	option od '1'
	option resolution '12'

